version: 2.1

executors:

  basic:
    docker:
      - image: 'funkyfisch/circleci-basic-linting:0.2'

workflows:

  on-pull-request-update:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: ${TRUNK_NAME}
      - lint:
          requires:
            - prepare
          filters:
            branches:
              ignore: ${TRUNK_NAME}
      - build:
          requires:
            - lint
          filters:
            branches:
              ignore: ${TRUNK_NAME}
      - unit-test:
          requires:
            - build
          filters:
            branches:
              ignore: ${TRUNK_NAME}

  on-trunk-merge:
    jobs:
      - publish:
          filters:
            branches:
              only: ${TRUNK_NAME}


jobs:

  prepare:
    executor: basic
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Store list of modified files against the trunk
          # In the case of feature branches/pull requests, we want to see the changes of
          # the current branch against the trunk not between two commits of the current branch,
          # since we can slip in changes that fail into the current branch and then commit
          # other changes that are successful and be allowed to commit them without realizing it
          # In the case that this is used after the merge, we want to compare the change with the
          # commit right before it
          command: |
            if [[ "$(git branch --show-current)" == "${TRUNK_NAME}" ]]
            then
              git diff \
                HEAD~1..HEAD \
                --name-only \
                --diff-filter=d > changelist
            else
              git diff \
                ${TRUNK_NAME}.."$(git branch --show-current)" \
                --name-only \
                --diff-filter=d > changelist
            fi
            cat changelist
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: basic
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run hadolint on modified dockerfiles, if any
          command: |
            if ! cat changelist | grep "\(Dockerfile\|\.dockerfile\)"
            then
              echo "No dockerfiles modified, skipping hadolint"
            else
              echo "Running hadolint"
            fi
      - run:
          name: Lint yml files
          command: |
            if ! cat changelist | grep "\.\(yml\|yaml\)"
            then
              echo "No yml files modified, skipping yaml linting"
            else
              yamllint $(cat changelist | grep "\.\(yml\|yaml\)")
            fi
      - run:
          name: Run shellcheck on shell scripts, if any
          command: |
            if ! cat changelist | grep "\.\(sh\|ash\|bash\)"
            then
              echo "No shell scripts modified, skipping shellcheck"
            else
              echo "Running shellcheck"
            fi
      - run:
          name: Lint docker-compose files
          command: |
            if ! cat changelist | grep "docker-compose*\.\(yml\|yaml\)"
            then
              echo "No docker compose files modified, skipping docker compose lint"
            else
              invalid_files_exist=0
              cat changelist \
                | grep "docker-compose*\.\(yml\|yaml\)" \
                | while read -r cf; do docker-compose -f $cf config; done
            fi


  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run: |
          if ! cat changelist | grep "\.js"
          then
            echo "No source files modified, skipping build"
            circleci-agent step halt
          fi
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm run build

  unit-test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run: |
          if ! cat changelist | grep "\.js"
          then
            echo "No source files modified, skipping test"
            circleci-agent step halt
          fi
      - run: npm run test:unit

  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - run: |
          echo "Publishing docker image!"
